# Generated by Django 3.1.5 on 2021-01-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
