# Generated by Django 3.1.5 on 2021-01-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210120_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='pin',
            field=models.CharField(max_length=6),
        ),
    ]
